services:
  server:
    container_name: sparkdouble-server-dev
    build:
      context: .
      target: full-deps
    environment:
      NODE_ENV: development
    secrets:
      - BOT_TOKEN
    volumes:
      - secretsdb:/usr/src/app/secretsdb/
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    ports:
      - 25565:25565
    command: npm run dev
secrets:
  BOT_TOKEN:
    file: ./BOT_TOKEN_DEV.txt
volumes:
  secretsdb:
